[project]
name = "arxiv_vector_search"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "sentence-transformers",
  "torch[device-gfx1201]",
  "google-cloud-storage",
  "langchain-text-splitters",
  "SQLAlchemy",
  "pgvector",
  "psycopg[binary,pool]",
  "pymupdf",
  "flash-attn",
  "packaging",
  "psutil",
  "ninja",
  "pip",
  "kagglehub[pandas-datasets]",
  "multiprocess",
  "dill",
  "packaging",
  "bitsandbytes",
  "peft",
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://rocm.nightlies.amd.com/whl-multi-arch/"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
triton = { index = "pytorch-rocm" }
xformers = { index = "pytorch-rocm" }
flash-attn = { git = "https://github.com/Dao-AILab/flash-attention/" }

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["arxiv_vector_search*"]
