[project]
name = "arxiv_vector_search"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "sentence-transformers",
  "torch",
  "triton-rocm",
  "triton",
  "google-cloud-storage",
  "langchain-text-splitters",
  "SQLAlchemy",
  "pgvector",
  "psycopg[binary,pool]",
  "pymupdf",
  "flash-attn",
  "packaging",
  "psutil",
  "ninja",
  "pip",
  "kagglehub[pandas-datasets]",
  "multiprocess",
  "dill",
  "packaging",
  "bitsandbytes",
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
triton-rocm = { index = "pytorch-rocm" }
triton = { index = "pytorch-rocm" }
xformers = { index = "pytorch-rocm" }
flash-attn = { git = "https://github.com/ROCm/flash-attention/" }

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["arxiv_vector_search*"]
